spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/omnisolve}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:potgress}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: public
    schemas: public
    create-schemas: true
  docker:
    compose:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${COGNITO_AUTHORITY:https://cognito-idp.us-east-1.amazonaws.com/us-east-1_liURZm1XY}
          jwk-set-uri: ${COGNITO_AUTHORITY:https://cognito-idp.us-east-1.amazonaws.com/us-east-1_liURZm1XY}/.well-known/jwks.json

server:
  port: ${PORT:${SERVER_PORT:5000}}

app:
  s3:
    bucket: ${DOCUMENT_BUCKET:dev-omnisolve-documents}
    region: ${AWS_REGION:us-east-1}
  security:
    jwt:
      enabled: ${JWT_ENABLED:true}
    cognito:
      audience: ${COGNITO_CLIENT_ID:c4af43ic7j8dfe70nr8cn79ei}
      domain: ${COGNITO_DOMAIN:https://us-east-1liurzm1xy.auth.us-east-1.amazoncognito.com}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:3000,https://dev-omnisolve-api.eba-n3eav3gy.us-east-1.elasticbeanstalk.com,https://prod-omnisolve-api.eba-nebwmcxk.us-east-1.elasticbeanstalk.com,https://d3s7bt9q3x42ay.cloudfront.net,https://omnisolve.africa}
